### ISSUE TITLE
The cost of InspectIT

### ISSUE THREAD

**Issue by xiaomutoun123** [inspectIT/inspectIT#104] opened 2016-06-08 14:41 UTC
Hi, 

Recently I plan to use InsptctIT and I have some questions: 

1. I want to use it for remote monitoring. So is there any requirement for the machine to install InspectIT? 

2. I've seen that your project group is sponsored by a German research institute. So may I have some information about what features you are developing for the moment and what new features you plan to add to it in the future? 

Thanks in advance for your response. 

Vladimir

**Comment by stefansiegl** [comment] 2016-06-09 14:19
Hi Vladimir,

Thank you for your questions. 

inspectIT is currently providing an agent for Java-based applications. This agent is applicable to all Java applications that use the Java version 5 and higher. There are no additional requirements. Have a look at the documentation at https://inspectit-performance.atlassian.net/wiki/display/DOC16/Installation+Guide for installation descriptions. 

Yes we are also running a BMBF research project called diagnoseIT that is supported by German government. You can find more details about the research project here: https://diagnoseit.github.io/ We work together with well-known universities and big German-based international companies. Also the results will be shared with the SPEC Research group (see https://research.spec.org/working-groups/devops-performance-working-group.html)

In diagnoseIT we are working on the automated diagnosis of traces (invocation sequences). Basically you just feed the traces to the system and diagnoseIT categorizes similiar problems and performs a root cause analysis for that. For more detail you might want to have a look at the material at https://diagnoseit.github.io/publications.html especially the slides sets that we presented and discussed at various conferences.

Apart from diagnoseIT inspectIT is constantly evolving. We try to get an updated roadmap at https://inspectit-performance.atlassian.net/wiki/display/ROAD - we also share all details on our detailed tickets in Jira: https://inspectit-performance.atlassian.net/projects/INSPECTIT/issues/INSPECTIT-1807?filter=allopenissues 

Your title suggests a question to the cost of inspectIT. inspectIT is completely free and licensed under Apache license v.2.

I hope this helps, please feel free to ask if sth was unclear

Regards,
Stefan

**Comment by stefansiegl** [comment] 2016-07-07 17:38
Hi @xiaomutoun123, is this question answered or do you have any additional points? I would like to close this issue if this is ok with you?

**Comment by xiaomutoun** [comment] 2016-07-08 07:38
Yes, you can close it. Thanks!

**Closed** 2016-07-08 14:35 UTC
