### ISSUE TITLE
Client is frozen everytime during the removal of registered agent

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#251] opened 2017-03-28 04:39 UTC
Our team found out that whether the version of client is 1.6.X or 1.7.X, all clients was frozen every time during the removal of agent.

Before we try to remove agent `jboss test`.
![default](https://cloud.githubusercontent.com/assets/1283378/24389343/595371f0-13b3-11e7-81e8-073b98fad646.png)

During the removal of agent....
![default](https://cloud.githubusercontent.com/assets/1283378/24389353/671bee98-13b3-11e7-98ef-f720be0698f2.png)
The client was frozen for more than one minutes.

Although we do not consider this phenomenon as a bug, it let us worried that the client may crash in any time.
Please consider to resolve this issue or provide us instructions to be sure that we wouldn't damage anything while the client is frozen.

**Comment by pbouillet** [comment] 2017-03-28 08:11
Thanks again for the report! This action is currently not implemented asynchronously and that's why the whole UI freezes while it's being processed. I created a ticket for this to fix this soon: https://inspectit-performance.atlassian.net/browse/INSPECTIT-2352 . 

I understand that it feels like the UI will crash with this, but actually it is just waiting for the operation to be completed and thus it won't lead to any problem.

**Comment by youjenli** [comment] 2017-03-29 06:00
My colleague told me that he hope the load-metrics-asynchronously function could be implement as soon as possible.
He feel that he often has to wait for client for a while in case he wants to open several metric view.

**Comment by pbouillet** [comment] 2017-03-29 06:03
Which metric view are you referring to? The deletion of an agent is not something you'll do all the time. And opening the "standard" views should be all done asynchronously.

**Comment by youjenli** [comment] 2017-03-29 06:40
Every view in `System overview` takes so much time to be render.
![system-overview](https://cloud.githubusercontent.com/assets/1283378/24441730/9574da18-148d-11e7-9bf4-07c9d965b7ae.png)

By the way, shouldn't we attach multiple clients to one CMR simultaneously?
It seems that every client got frozed together when anyone of them established a synchronous connection.

**Comment by pbouillet** [comment] 2017-03-29 06:57
It can take some time to get the data, but all of this is done in the background. I just checked it again. No matter how long the server takes to respond, the UI was fully usable for me.

And yes, it is completely intended to attach multiple clients to one single CMR.

**Comment by ivansenic** [comment] 2017-03-29 07:10
Hi @youjenli,

The problem with system data is that it's basically not intended to be used in the way you do. Usually if you have a lot of agents you would go for using influxDB. This way all the system data is written there and it's much more "responsive". When you don't use influxDB we write everything to the H2 database and this grows really fast and get slower and slower. I see on your screen shot that database is 1.5GB for you already, so I really propose to consider writing long-term monitoring data there and avoid the internal database because it simply can not scale.

**Comment by youjenli** [comment] 2017-03-29 10:12
Hi @ivansenic

What should I expect after setting up Influxdb for InspectIT?
What will CMR do after I assign Influxdb as it's database?
Will it transfer previous analysis data to Influxdb?

My client have been frozen for over 10 minutes when I click memory view after following [these steps][long term data persistence configuration] to setup Influxdb **1.0** for CMR.

![influxdb](https://cloud.githubusercontent.com/assets/1283378/24449821/21b5fecc-14ab-11e7-953d-95321cc175c5.png)

[long term data persistence configuration]: https://inspectit-performance.atlassian.net/wiki/display/DOC17/Long-term+Data+Persistence+Configuration "long term data persistence configuration"

**Comment by ivansenic** [comment] 2017-03-29 10:39
Hi @youjenli.

If you activate influxDB all the long-term monitoring data like CPU, Memory, etc will be saved in influxDB. Then you would ideally install Grafana to visualize the data from the influxDB. We offer some predefined [dashboards](https://inspectit-performance.atlassian.net/wiki/display/DOC17/Integrate+inspectIT+default+dashboards). This would mean that you would use Grafana for displaying the system based metrics for example. Please read our [Setup Monitoring](https://inspectit-performance.atlassian.net/wiki/display/DOC17/Setup+Monitoring) section I think it suits your use case and checkout dashboards that you get out-of-the-box.

**Will it transfer previous analysis data to Influxdb?** Unfortunately not. You could manually read data from the H2 database that you have there and transfer it to the influxDB if you really need it, but I guess it's huge amount of work to make this done.

There is one additional benefit in using influxDB. If you define your business context settings (Configuration Perspective -> Business Context Manager), we would also write information about Applications and Business transactions to the influxDB. This would basically solve your problem mentioned in the #252 with respect to URI aggregation. You can map certain URIs to the business transaction and then get a nice overview on the transactions which is currently missing in the user interface. Looks like: 

![image2016-9-13 15-10-2](https://cloud.githubusercontent.com/assets/10600041/24450722/3af0ea98-147c-11e7-8668-445832cd61f1.png)

**Comment by youjenli** [comment] 2017-03-30 10:27
Hi @ivansenic

The halt of client I mentioned in previous comments had continued for over 20 hours until I kill my client and CMR in today afternoon.
It's weired that I didn't found any log message in CMR which looks taking part in this problem, except that there are numerous lines of message which describe the activity of connections.

What may brought out this halt? Would it because of network delay between CMR and Influxdb?

In addition to this issue, today I discovered that it takes more than 10 seconds to open memory view of monitoring target after I use Influxdb to store metrics yesterday.
My client had throwed exception eventually one time when I try to open memory view.

```
inspectIT Version: 1.7.8.91
Operating system: Windows 7 6.1 (amd64)
Java version: Oracle Corporation 1.7.0-u80-unofficial
Exception type: org.eclipse.swt.SWTException
Exception message: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
Stack trace (limited): org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
        at org.eclipse.swt.SWT.error(SWT.java:4361)
        at org.eclipse.swt.SWT.error(SWT.java:4276)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4144)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
        at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
        at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
        at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
        at rocks.inspectit.ui.rcp.Application.start(Unknown Source)
```

By the way, even if the memory view has been render properly, I still can't see memory usage graph.

![2017-3-30 06-25-21](https://cloud.githubusercontent.com/assets/1283378/24500040/8515bb80-1576-11e7-8ca6-dce23c3d8312.png)

Is it because we use Oracle JDK 1.6.0_45 to run monitoring target?

**Comment by ivansenic** [comment] 2017-03-30 11:23
Hi @youjenli,

I am really sorry that you are experiencing this problems, it's unfortunate that you did not set up monitoring approach from the start.

I am sure that the problem is internal H2 database. You overfilled it with data and querying it becomes too expensive. I really suggest that you delete this database by clearing the ```[CMR base]/db/``` folder (CMR must be stopped for this to work).

The reason you are not seeing the data in the Memory View now is that all data is in the influxDB and the view can only be used to display data from the database. It's like this if you write to H2 you can use inspectIT views, if you write to infludxDB you need to setup Grafana and dashboards. I know it's a bit confusing, but it will be improved in the future.

**Comment by youjenli** [comment] 2017-03-31 04:22
Thanks a lot!

If so then I wonder what purpose are those features like `Copy Repository Buffer to Storage`, `Start Recording`, `Define new storage` designed for in case of using Influxdb as storage system of InspectIT?
Are they combined to provide a sampling-like mechanism for monitored platform?

**Comment by ivansenic** [comment] 2017-03-31 06:55
You will still have lot of the diagnosis data saved in the buffer even if you are writing to influxDB. This would enable you do check specific invocations, analyze problems, etc. Idea is that in future system automatically detect anomalies in your response times (or other metrics) and start automatic recording to save you all the data that was related to this time-frame.

One more thing I forgot to mention as benefit of using influxDB and that's that you can also set alerting with fixed thresholds (Configuration perspective -> Alerting Manager). You might want to check that as well.

**Comment by ivansenic** [comment] 2017-06-16 09:30
Will be fixed in [INSPECTIT-2457](https://inspectit-performance.atlassian.net/browse/INSPECTIT-2457)

**Closed** 2017-07-07 10:31 UTC
Labels: bug
