### ISSUE TITLE
Communication between agent and CMR fails

### ISSUE THREAD

**Issue by MM26** [inspectIT/inspectIT#158] opened 2016-09-03 11:29 UTC
Hi,
I am exploring InspectIT (version:1.7.1.84)for my current project. Read through documentation
1. CMR & UI - installed on my laptop. CMR repository started with IP:localhost & Port: 8192. Status is ONLINE
2. I am trying to install agent (inspectit-agent-sun1.5-1.7.1.84.zip) on RHEL6.5. I have modified run.sh file (jboss) as below
### set INSPECTIT_AGENT_HOME="/root/IT/agent"
export INSPECTIT_AGENT_HOME

set INSPECTIT_JAVA_OPTS="-Xbootclasspath/p:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -javaagent:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -Dinspectit.repository=<laptop IP>:9070 -Dinspectit.agent.name=Instance1"
export INSPECTIT_JAVA_OPTS

# integrate inspectit java options with the java options of JBoss
set JAVA_OPTS="${INSPECTIT_JAVA_OPTS} ${JAVA_OPTS}"

3. Restarted JBOSS

4.  I am verifying the communication between agent and CMR 
_[root@oracle12 bin]# java -javaagent:/root/IT/agent/inspectit-agent.jar -Dinspectit.config=/root/IT/agent/config -version
Sep 03, 2016 4:32:36 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Starting initialization...
16:33:46.674 [main] INFO rocks.inspectit.agent.java.SpringAgent - Location of inspectit-agent.jar set to: /root/IT/agent/inspectit-agent.jar
2016-09-03 16:33:46,909: [inspectIT] 291    [           main] INFO  spectit.agent.java.SpringAgent - Initializing Spring on inspectIT Agent...
2016-09-03 16:33:48,247: [inspectIT] 1629   [           main] INFO  nfig.impl.ConfigurationStorage - Agent name set to: inspectIT
2016-09-03 16:33:48,253: [inspectIT] 1635   [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
Sep 03, 2016 4:33:48 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes ...
Sep 03, 2016 4:33:48 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes complete...
Sep 03, 2016 4:33:48 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Initialization complete...
Sep 03, 2016 4:33:48 PM rocks.inspectit.agent.java.javaagent.JavaAgent analyzeAlreadyLoadedClasses
INFO: inspectIT Agent: Instrumentation of core classes finished...
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
[root@oracle12 bin]#_

Logs:
2016-09-03 16:33:48,247: 1629   [           main] INFO  nfig.impl.ConfigurationStorage - Agent name set to: inspectIT
2016-09-03 16:33:48,253: 1635   [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
org.springframework.beans.factory.BeanInitializationException: inspectIT agent must be initialized with IP and port of the CMR via JVM parameters.
        at rocks.inspectit.agent.java.config.impl.ConfigurationStorage.afterPropertiesSet(ConfigurationStorage.java:375)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
        ... 22 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationStorage' defined in URL [jar:file:/root/IT/agent/inspectit-agent.jar!/rocks/inspectit/agent/java/config/impl/ConfigurationStorage.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanInitializationException: inspectIT agent must be initialized with IP and port of the CMR via JVM parameters.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at rocks.inspectit.agent.java.SpringAgent.initSpring(SpringAgent.java:146)
        at rocks.inspectit.agent.java.SpringAgent.<init>(SpringAgent.java:105)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at rocks.inspectit.agent.java.javaagent.JavaAgent.premain(JavaAgent.java:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

Please let me know, what is wrong here.

**Comment by pbouillet** [comment] 2016-09-03 11:35
Hi @MM26,

this should be easy to fix. You are missing the definition of the IP / hostname in the inspectit.repository configuration:

> -Dinspectit.repository=:9070

It should look like (if the agent and the CMR both run locally, otherwise, just replace localhost with the correct IP or hostname):
**-Dinspectit.repository=localhost:9070**

Let me know if this works.

**Comment by MM26** [comment] 2016-09-05 09:24
Hi pbouillet,

Changed localhost to IP of laptop. Ping is working fine from laptop to server & vice-versa.
Error: inspectIT agent initialization failed. Agent will not be active.

[root@oracle12 bin]# java -javaagent:/usr/local/inspectIT/agent/inspectit-agent.jar -Dinspectit.config=/usr/local/inspectIT/agent/config -version
Sep 05, 2016 2:44:24 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Starting initialization...
14:45:39.935 [main] INFO rocks.inspectit.agent.java.SpringAgent - Location of inspectit-agent.jar set to: /usr/local/inspectIT/agent/inspectit-agent.jar
2016-09-05 14:45:40,746: [inspectIT] 1046   [           main] INFO  spectit.agent.java.SpringAgent - Initializing Spring on inspectIT Agent...
2016-09-05 14:45:42,457: [inspectIT] 2757   [           main] INFO  nfig.impl.ConfigurationStorage - Agent name set to: inspectIT
2016-09-05 14:45:42,465: [inspectIT] 2765   [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
Sep 05, 2016 2:45:42 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes ...
Sep 05, 2016 2:45:42 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes complete...
Sep 05, 2016 2:45:42 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Initialization complete...
Sep 05, 2016 2:45:42 PM rocks.inspectit.agent.java.javaagent.JavaAgent analyzeAlreadyLoadedClasses
INFO: inspectIT Agent: Instrumentation of core classes finished...
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**Comment by ivansenic** [comment] 2016-09-05 10:05
Hi @MM26 ,

What version are you using? The configuration folder is not anymore needed, can you switch to the latest stable version 1.6.9? Also logs from the _agent/logs/_ folder would be helpful.

**Comment by pbouillet** [comment] 2016-09-05 10:45
As you mentioned version 1.7 in the beginning, you just need to add the inspectit.repository configuration in the jvm parameters and remove the config (as this was in the early 1.6 versions used and is now completely removed):

`java -javaagent:/usr/local/inspectIT/agent/inspectit-agent.jar -Dinspectit.repository=localhost:9070 -version`

**Comment by MM26** [comment] 2016-09-05 11:38
Just referred the doc for 1.7, what is [path-to-config-folder] ? What value are we supposed to give here.

# inspectIT Settings
INSPECTIT_AGENT_HOME="[path-to-inspectit-agent-home]"
INSPECTIT_CONFIG_HOME="[path-to-config-folder]"
INSPECTIT_JAVA_OPTS="-Xbootclasspath/p:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -javaagent:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -Dinspectit.config=${INSPECTIT_CONFIG_HOME}"
JAVA_OPTS="${INSPECTIT_JAVA_OPTS} ${JAVA_OPTS}"

**Comment by ivansenic** [comment] 2016-09-05 11:56
Hi @MM26,

That's obviously mistake in our documentation, as this is not valid anymore. I will try to update these pages where the configuration folder is mentioned. The generic JBoss/Wildfly setup you can find here: https://inspectit-performance.atlassian.net/wiki/pages/viewpage.action?pageId=54657070 (correct docs). The sub-pages for specific version are having old setup instructions. 

Sorry for inconvenience.

**Comment by MM26** [comment] 2016-09-05 14:46
Hi ivansenic,

Earlier I have tried the same. I have changed settings in run.sh as
CMR @ laptop : Added as localhost:8191 and status=ONLINE

set INSPECTIT_AGENT_HOME="/usr/local/inspectIT/agent"
export INSPECTIT_AGENT_HOME
set INSPECTIT_JAVA_OPTS="-Xbootclasspath/p:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -javaagent:${INSPECTIT_AGENT_HOME}/inspectit-agent.jar -Dinspectit.repository=<IP of laptop>:8191 -Dinspectit.agent.name=Instance1"
export INSPECTIT_JAVA_OPTS
set JAVA_OPTS="${INSPECTIT_JAVA_OPTS} ${JAVA_OPTS}"

What is wrong in this?

cmd execution:
[root@oracle12 ~]# java -javaagent:/usr/local/inspectIT/agent/inspectit-agent.jar -Dinspectit.config=/usr/local/inspectIT/agent/config -version
Sep 05, 2016 8:10:01 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Starting initialization...
20:11:11.705 [main] INFO rocks.inspectit.agent.java.SpringAgent - Location of inspectit-agent.jar set to: /usr/local/inspectIT/agent/inspectit-agent.jar
2016-09-05 20:11:12,052: [inspectIT] 431    [           main] INFO  spectit.agent.java.SpringAgent - Initializing Spring on inspectIT Agent...
2016-09-05 20:11:13,471: [inspectIT] 1850   [           main] INFO  nfig.impl.ConfigurationStorage - Agent name set to: inspectIT
2016-09-05 20:11:13,476: [inspectIT] 1855   [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
Sep 05, 2016 8:11:13 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes ...
Sep 05, 2016 8:11:13 PM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes complete...
Sep 05, 2016 8:11:13 PM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Initialization complete...
Sep 05, 2016 8:11:13 PM rocks.inspectit.agent.java.javaagent.JavaAgent analyzeAlreadyLoadedClasses
INFO: inspectIT Agent: Instrumentation of core classes finished...
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
[root@oracle12 ~]#


Logs:
2016-09-05 20:13:11,050: 1821   [           main] INFO  nfig.impl.ConfigurationStorage - Agent name set to: inspectIT
2016-09-05 20:13:11,056: 1827   [           main] ERROR spectit.agent.java.SpringAgent - inspectIT agent initialization failed. Agent will not be active.
org.springframework.beans.factory.BeanInitializationException: inspectIT agent must be initialized with IP and port of the CMR via JVM parameters.
        at rocks.inspectit.agent.java.config.impl.ConfigurationStorage.afterPropertiesSet(ConfigurationStorage.java:375)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
        ... 22 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'configurationStorage' defined in URL [jar:file:/usr/local/inspectIT/agent/inspectit-agent.jar!/rocks/inspectit/agent/java/config/impl/ConfigurationStorage.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanInitializationException: inspectIT agent must be initialized with IP and port of the CMR via JVM parameters.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at rocks.inspectit.agent.java.SpringAgent.initSpring(SpringAgent.java:146)
        at rocks.inspectit.agent.java.SpringAgent.<init>(SpringAgent.java:105)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at rocks.inspectit.agent.java.javaagent.JavaAgent.premain(JavaAgent.java:98)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

**Comment by pbouillet** [comment] 2016-09-05 15:24
I am a little bit confused about your setup. You change the run.sh file but then execute java directly? As mentioned above in my comment, just execute the following and you will see if it basically works for you:

`java -javaagent:/usr/local/inspectIT/agent/inspectit-agent.jar -Dinspectit.repository=localhost:9070 -Dinspectit.agent.name=Instance1 -version`

And if you want to create a working run.sh, then just follow my initial comment about your wrong **-Dinspectit.repository=:8191** definition and just add localhost in there.

**Comment by MM26** [comment] 2016-09-06 04:19
Thanks pbouillet :-)
Connection established, will proceed further implementation now. Documentation need to be changed.

Sep 06, 2016 9:31:00 AM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Starting initialization...
09:32:17.341 [main] INFO rocks.inspectit.agent.java.SpringAgent - Location of inspectit-agent.jar set to: /usr/local/inspectIT/agent/inspectit-agent.jar
2016-09-06 09:32:17,643: [inspectIT] 373    [           main] INFO  spectit.agent.java.SpringAgent - Initializing Spring on inspectIT Agent...
2016-09-06 09:32:19,002: [inspectIT] 1732   [           main] INFO  nfig.impl.ConfigurationStorage - Repository information found in the JVM parameters: IP=<IP> Port=9070
2016-09-06 09:32:19,002: [inspectIT] 1732   [           main] INFO  nfig.impl.ConfigurationStorage - Repository definition added. Host: <IP> Port: 9070
2016-09-06 09:32:19,003: [inspectIT] 1733   [           main] INFO  nfig.impl.ConfigurationStorage - Agent name found in the JVM parameters: AgentName=Instance1
2016-09-06 09:32:19,047: [inspectIT] 1777   [           main] INFO  nfig.impl.ConfigurationStorage - Agent name set to: Instance1
2016-09-06 09:32:19,209: [inspectIT] 1939   [           main] INFO  izer.schema.ClassSchemaManager - ||-Class Schema Manager started..
2016-09-06 09:32:19,796: [inspectIT] 2526   [           main] INFO  nection.impl.KryoNetConnection - KryoNet: Connecting to 10.175.28.95:9070
2016-09-06 09:32:20,050: [inspectIT] 2780   [           main] INFO  nection.impl.KryoNetConnection - KryoNet: Connection established!
2016-09-06 09:32:20,691: [inspectIT] 3421   [           main] INFO  nfig.impl.ConfigurationStorage - Agent configuration added with following configuration interface properties:
2016-09-06 09:32:20,691: [inspectIT] 3421   [           main] INFO  nfig.impl.ConfigurationStorage - Assigned environment: Default Environment
2016-09-06 09:32:20,691: [inspectIT] 3421   [           main] INFO  nfig.impl.ConfigurationStorage - Active profiles:
2016-09-06 09:32:20,692: [inspectIT] 3422   [           main] INFO  nfig.impl.ConfigurationStorage - |-[Common] Exclude Classes
2016-09-06 09:32:20,692: [inspectIT] 3422   [           main] INFO  nfig.impl.ConfigurationStorage - |-[Common] HTTP
2016-09-06 09:32:20,692: [inspectIT] 3422   [           main] INFO  nfig.impl.ConfigurationStorage - |-[Common] SQL
2016-09-06 09:32:20,692: [inspectIT] 3422   [           main] INFO  nfig.impl.ConfigurationStorage - Options:
2016-09-06 09:32:20,693: [inspectIT] 3423   [           main] INFO  nfig.impl.ConfigurationStorage - |-class loading delegation: true
2016-09-06 09:32:20,693: [inspectIT] 3423   [           main] INFO  nfig.impl.ConfigurationStorage - |-enhanced exception sensor: false
2016-09-06 09:32:20,693: [inspectIT] 3423   [           main] INFO  nfig.impl.ConfigurationStorage - Class-cache exists on the server: false
2016-09-06 09:32:20,861: [inspectIT] 3591   [           main] INFO  spectit.agent.java.SpringAgent - Spring successfully initialized
2016-09-06 09:32:20,863: [inspectIT] 3593   [           main] INFO  spectit.agent.java.SpringAgent - Using agent version 1.7.1.84.
Sep 06, 2016 9:32:20 AM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes ...
Sep 06, 2016 9:32:20 AM rocks.inspectit.agent.java.javaagent.JavaAgent preloadClasses
INFO: Preloading classes complete...
Sep 06, 2016 9:32:20 AM rocks.inspectit.agent.java.javaagent.JavaAgent premain
INFO: inspectIT Agent: Initialization complete...
Sep 06, 2016 9:32:44 AM rocks.inspectit.agent.java.javaagent.JavaAgent analyzeAlreadyLoadedClasses
INFO: inspectIT Agent: Instrumentation of core classes finished...
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
2016-09-06 09:32:44,146: [inspectIT] 26876  [       Thread-6] INFO  ent.java.core.impl.CoreService - Shutdown initialized, sending remaining data
2016-09-06 09:32:44,148: [inspectIT] 26878  [efresher-thread] ERROR ent.java.core.impl.CoreService - Sensor refresher was interrupted!
2016-09-06 09:32:44,148: [inspectIT] 26878  [-sending-thread] ERROR ent.java.core.impl.CoreService - Sending thread interrupted and shuting down!
2016-09-06 09:32:44,148: [inspectIT] 26878  [reparing-thread] ERROR ent.java.core.impl.CoreService - Preparing thread interrupted and shutting down!
2016-09-06 09:32:44,150: [inspectIT] 26880  [       Thread-6] INFO  ent.java.core.impl.CoreService - Unregistering the Agent

**Comment by ivansenic** [comment] 2016-09-06 05:15
@pbouillet, @MM26 Documentation is updated. As the problem is solved I will close this issue.

**Closed by ivansenic** 2016-09-06 05:15 UTC
