### ISSUE TITLE
System Overview dashboard can not show metrics of agents which has dot notation in it's name.

### ISSUE THREAD

**Issue by youjenli** [inspectIT/inspectIT#271] opened 2017-05-02 04:24 UTC
Metrics gathered by our agent which named **ubuntu16.04-openjdk8-petclinic-rest** has never been displayed by Grafana on System Overview dashboard.

![2017-5-2- -10-30-02](https://cloud.githubusercontent.com/assets/1283378/25603825/fe35a596-2f31-11e7-80f3-ca4609b5f26b.png)

Since those metrics had already been recorded into Influxdb and every queries of this dashboard reference the `AgentName` variable defined in Templating configuration, I guess that this is probably because the name of our agent includes dot notation.
This might bring out some problem at the time Grafana generate queries to fetch data from Influxdb.

![influxdb 2017-5-2- -10-31-07](https://cloud.githubusercontent.com/assets/1283378/25603836/15fbe820-2f32-11e7-878d-427060f356bf.png)

![agent regex 2017-5-2- -10-34-00](https://cloud.githubusercontent.com/assets/1283378/25603838/1f5fc8aa-2f32-11e7-9a28-7d6b5a41a7af.png)

Thus I tried to resolve this issue by removing the dot notation from the name of agent. And now the System Overview dashboard looks fine.

![-2017-5-2- -10-57-01](https://cloud.githubusercontent.com/assets/1283378/25603847/2cd1544a-2f32-11e7-9767-9e76201b1b05.png)

Although dot notation is not mandatory in our naming rules for InspectIT agent, I'd like to know whether there's any approach which can resolve this issue without restricting the characters available for use?

**Comment by ivansenic** [comment] 2017-05-03 07:36
Confirmed as a bug, we need to escape the special characters in the names. Ticket: https://inspectit-performance.atlassian.net/browse/INSPECTIT-2399

@youjenli Thanks

**Comment by mariusoe** [comment] 2017-05-22 15:09
@youjenli - Can you verify that this problem is related to the characters in the agent name? I tested it and these characters should already be escaped because they are used as a template variable.

Maybe there was another problem (e.g. related to the specified time interval).

I will close this ticket for now but feel free to reopen it, if there is still a problem with this. :)

**Closed by mariusoe** 2017-05-22 15:09 UTC
Labels: bug

**Comment by youjenli** [comment] 2017-07-11 07:42
@mariusoe 
Sorry, I just stopped using dot notation in agent's name after I raised up this issue.
